workflows:
  build-android-expo:
    name: Build Android APK (Expo)
    environment:
      vars:
        EXPO_CLI_TOKEN: EncryptedString
    triggering:
      events: [push, pull_request]
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Prebuild (Expo)
        script: |
          npx expo prebuild --platform android
      - name: Build with EAS (if using EAS)
        script: |
          # This uses EAS - if you prefer classic build, replace with `expo build:android`
          npx eas build -p android --non-interactive
    artifacts:
      - build/*.apk