workflows:
  build-android:
    name: Build Android APK
    environment:
      node: 16
      vars:
        EXPO_ANDROID_KEYSTORE_PASSWORD: ""
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          npx expo export --platform android
    artifacts:
      - build/**/*.apk
